$(document).ready(function(){
	abm.menu();
	abm.index();

	$("#link-list-books").on("click",function(){
		books.showContainClean();
		$("#books").removeClass("hidden");
		books.list();
	});
	$("#link-create-book").on("click",function(){
		books.showContainClean();
		$("#create-book").removeClass("hidden");
		books.cleanBookForm();
		books.create();
	});
	$("#link-list-authors").on("click",function(){
		authors.showContainClean();
		$('#authors').removeClass("hidden");
		authors.list();
	})
	$("#link-create-author").on("click",function(){
		books.showContainClean();
		$("#create-author").removeClass("hidden");
		authors.cleanAuthorForm();
		authors.create();
	})
});